### ISSUE TITLE
Cannot Resolve ObjectOrReference<Header>

### ISSUE THREAD

**Issue by CodingFlow** [x52dev/oas3-rs#13]
Cannot call `resolve` on `ObjectOrReference<Header>`. In a minimal example project, the compiler error message:

> the method `resolve` exists for enum `ObjectOrReference<Header>`, but its trait bounds were not satisfied
the following trait bounds were not satisfied:
`oas3::spec::Header: FromRef`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B0%5D?0#file%3A%2F%2F%2Fc%253A%2FUsers%2FBlue%2FDocuments%2FCoding%2FRust%2Foas3_header_no_ref%2Fsrc%2Fmain.rs)
header.rs(20, 1): doesn't satisfy `oas3::spec::Header: FromRef`

The code showing the issue with `oas3 = "0.4"` in cargo.toml:

```rust
fn main() {
    let mut spec = oas3::from_path("path").unwrap();

    let path = spec.paths.pop_first();
    let operation = path.unwrap().1.get.unwrap();
    let mut responses = operation.responses(&spec);
    let response = responses.pop_first().unwrap();
    let mut headers_refs = response.1.headers;
    let header_ref = headers_refs.pop_first().unwrap();
    let header = header_ref.1.resolve(&spec); // compile error here
}

```

I'd appreciate if someone could at least provide a workaround until the issue is fixed. 🙇

**Comment by robjtede** [comment]
done and released in v0.8: https://github.com/x52dev/oas3-rs/releases/tag/oas3-v0.8.0
