### ISSUE TITLE
Support deserializing `null` value in `enum` array for nullable multi-types

### ISSUE THREAD

**Issue by vegardgs-ksat** [x52dev/oas3-rs#135]
According to the referenced JSON Schema Validation for OAS3.1, the [enum property](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.2) can be of any valid type (presumably matching the multi-valued `type` fields, including `null`.

This was observed in the wild when attempting to parse [GitHub OpenAPI 3.1 specification](https://github.com/github/rest-api-description/blob/main/descriptions-next/api.github.com/api.github.com.json), which includes schemas with multi-type, where one type is `null`.

This can be demonstrated with the following:
```rust
use oas3::spec::ObjectSchema;

fn main() {
    let json = serde_json::json!({
        "type": ["string", "null"],
        "enum": ["one", null]
    });

    let object: ObjectSchema = serde_json::from_value(json).unwrap();
}
```

produces
```
called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a string", line: 0, column: 0)`
```

The same is true when done through the `ObjectOrReference<ObjectSchema>`, but with a more diffuse error message:

```rust
use oas3::spec::{ObjectOrReference, ObjectSchema};

fn main() {
    let json = serde_json::json!({
        "type": ["string", "null"],
        "enum": ["one", null]
    });

    let reference: ObjectOrReference<ObjectSchema> = serde_json::from_value(json).unwrap();
}
```
produces
```
called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum ObjectOrReference", line: 0, column: 0)
```

**Comment by robjtede** [comment]
this was fixed but unreleased

just released v0.13.0 which adds support for null `enum` and `const` values
