### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by danifujii** [x52dev/oas3-rs#2]
Hello.
I was wondering if you could release the latest version of the code to crates. I am running an issue with a dependency that is being fetched when it shouldn't, which was fixed on [this commit](https://github.com/robjtede/oas3-rs/commit/06b675e88bfc8b85a9d590dfc59e7dd1e1fe69ac). However, the latest version in crates is from a few days before that.

Thank you in advance,
Daniel

**Comment by robjtede** [comment]
https://crates.io/crates/oas3/0.5.0
