### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by isg8** [x52dev/oas3-rs#43]
Hi, thank you for creating this crate - very useful! I am trying to see if i can extract custom extensions (in my case for Operation struct). According to spec, you should be able to add custom extensions:

https://github.com/OAI/OpenAPI-Specification/blob/HEAD/versions/3.1.0.md#specification-extensions

**Comment by Groovin-Dev** [comment]
+1

**Comment by TheKingdom36** [comment]
Have a project which could use this feature, will take a crack at implementing.

**Comment by robjtede** [comment]
Implemented and released in v0.7: https://github.com/x52dev/oas3-rs/releases/tag/oas3-v0.7.0
