### ISSUE TITLE
Expose More Types Publicly

### ISSUE THREAD

**Issue by CodingFlow** [x52dev/oas3-rs#5]
Forgive me if this has to do with me being a newbie Rustacean.

I'm trying to inspect the open API spec `Spec` struct more dynamically and would like to extract the logic into separate functions. But I'm running into an issue of not being able to declare types returned by oas3 functions in the function parameter due to private accessibility. Here's an example code to demonstrate:

```rust
fn main() {
    let spec = match oas3::from_path("./src/workflow_spec.yaml") {
        Ok(spec) => spec,
        Err(_) => panic!("unable to read open API spec file"),
    };

    spec.paths.into_iter().for_each(|path| {
        path.1.methods().into_iter().for_each(|method| {
            generate_code(path, method);
        });
    });
}

fn generate_code(path: (String, PathItem), method: (Method, &Operation)) -> _ {
    todo!()
}
```

in `generate_code` , The types `PathItem` and `Operation` are not accessible to declare them in the function signature. It seems it is because the `spec` module they are in is not public Should these types become accessible?

**Comment by CodingFlow** [comment]
It seems the latest version of the crate published on crates.io is not up-to-date with master. [In master, the `spec` module is public](https://github.com/x52dev/oas3-rs/blob/a6b4c0bb25ef2b3d7a5364858673f82d70a0f0f5/src/lib.rs#L20), but not public on version 0.2.1 on crates.io. Can we get the latest changes in master published to crates.io as a new version?

**Comment by robjtede** [comment]
Published! https://crates.io/crates/oas3/0.3.0
