### ISSUE TITLE
Support extensions for operation object

### ISSUE THREAD

**Issue by isg8** [x52dev/oas3-rs#78]
Thank you for implementing https://github.com/x52dev/oas3-rs/issues/43 but it seems that operation object still doesn't support this. Can we add it to that object too?

**Comment by robjtede** [comment]
fixed in 8fdf3a56ca0b71e5ac1a0b6539b660c7d4363049

**Comment by robjtede** [comment]
released in v0.9.0: https://github.com/x52dev/oas3-rs/releases/tag/oas3-v0.9.0
