### ISSUE TITLE
Missing support for `const` annotation

### ISSUE THREAD

**Issue by RReverser** [x52dev/oas3-rs#96]
JSON Schema that OpenAPI is based on, supports a special `const` keyword to denote values that is similar to `minimum` or `maximum` but denotes that a type can hold only one value. https://json-schema.org/understanding-json-schema/reference/const

Right now those keywords seem to be silently ignored (which seems like a separate problem - shouldn't it report some error or diagnostics about unsupported keywords?).

**Comment by robjtede** [comment]
made the code change but i'm apprehensive to make a breaking release with just this change in it, would you be okay just using `enum: [value]` for now ?

**Comment by RReverser** [comment]
Hm I could, yeah, but why would this be a breaking release? It seems strictly append-only?

**Comment by robjtede** [comment]
Adding pub fields to pub structs is breaking, since manual constructions won't have these fields.

**Comment by RReverser** [comment]
Ugh that's true. Maybe for the future worth adding a private `_prevent_construction: (),` field to prevent manual construction, so that you could make further additions without having to worry about breaking releases?

That way users will still have direct access to all the fields, but will have to go via `Schema::default()` + manual field initializers for construction.

**Comment by robjtede** [comment]
The canonical way to do so is the `#[non_exhaustive]` attibute.

I've avoided it just because these structures _should_ be complete and relateively stable. Tell you what I'll have a scan through the JSON Schema Validation spec and see if there's anything else missing, then cut a release.

**Comment by RReverser** [comment]
> The canonical way to do so is the `#[non_exhaustive]` attibute.

That one only covers pattern matching, but doesn't protect from construction.

**Comment by RReverser** [comment]
> Tell you what I'll have a scan through the JSON Schema Validation spec and see if there's anything else missing, then cut a release.

SGTM. As I said above, I think it might be useful to return an error on any unexpected fields except vendor extensions (which all must be under `x-` prefix anyway). That would help catch new unsupported features quicker than silently skipping over them.

**Comment by robjtede** [comment]
It does protect from construction. See [the reference.](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute)

> return an error on any unexpected fields

This isn't something I want to do with the structures in this crate.

**Comment by RReverser** [comment]
> It does protect from construction. See [the reference.](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute)

Ah I guess I always tried it only within the same crate. Fair enough.

> This isn't something I want to do with the structures in this crate; it turns the dial too far in the other direction for my taste.

Hm but if the entire JSON Schema should be already implemented, then it shouldn't cause issues, right?

Alternatively, if you're strictly opposed to making it an error, how about collecting any unknown fields into a `BTreeMap<String, serde_yaml::Value>`? That would also allow consumers to at least catch any unexpected data instead of it being skipped over.

**Comment by robjtede** [comment]
released in v0.11
